### ISSUE TITLE
Cannot read properties of undefined (reading 'labelKey')

### ISSUE THREAD

**Issue by cwwjsyc** [revolist/revogrid-column-select#10]
`
column_schema: [
        {
          prop: "name",
          name: "ID",
        },
        {
          prop: "details",
          name: "Name",
        }, {
          prop: "drops",
          name: "Data",
          labelKey: 'show',
          valueKey: 'data',
          source: [
            {show: 'According', data: 'a'},
            {show: 'Over', data: 'b'},
            {show: 'Source', data: 's'}
          ],
          columnType: 'select'
        }
      ],
`
[https://codesandbox.io/s/8zkd4](url)
Render Error. Like Demo.

**Comment by satyavh** [comment]
+1

**Comment by christianholland** [comment]
+1

**Comment by revolist** [comment]
Can not reproduce anymore.
