### ISSUE TITLE
Global prototype functions on Array are used as values

### ISSUE THREAD

**Issue by alinoil** [revolist/revogrid-column-select#11]
I have 2 global protoype functions on Array and they are being used as values in the dropdown. With undefined as label.
![image](https://user-images.githubusercontent.com/6596304/182866229-81f066e9-046a-4e4a-bd4b-07adf53cae03.png)

<img width="339" alt="image" src="https://user-images.githubusercontent.com/6596304/182866719-1d6eb694-6c1a-4583-84fd-cc9d847dd400.png">

**Comment by revolist** [comment]
Please mutate your array to keep array pure
