### ISSUE TITLE
How to update items in dropdown/selector based on another cells value?

### ISSUE THREAD

**Issue by christianholland** [revolist/revogrid-column-select#12]
Hi there,

I am using the `SelectTypePlugin()` to add a dropdown/selector to revogrid columns. Would it be possible to update the items in the dropdown/selector based on another cells value?

```
        {
            prop: "type",
            name: "Type",
            source: ["Volume", "Mass", "Length"]
            columnType: "select",
        },
        {
            prop: "units",
            name: "Units",
            source: ["ml, "L", "g", "kg", "m", "km"] 
            columnType: "select",
        }
```

For instance, if for the `Type` column `Volume` is selected only the items `mL` and `L` should appear in the `Units` column. Accordingly if `Mass` is selected only `g` and `kg` should be listed, etc...

I was hoping for a callbach function similiar to how the `readonly` key can be adjusted for a single cell like it was described in issue [#323](https://github.com/revolist/revogrid/issues/323#issuecomment-1152358904). However, it seems that the `source` key only accepts a list and not a function ([source code](https://github.com/revolist/revogrid-column-select/blob/220e7cbb0f3b266eb9b3d0634b01b8eabcd88d36/src/type.ts#L3)). 

Is there a workaround to archive the desired result or do you think it might be important enough to implement the callback function logic for one of the next releases?

Thanks,
Christian

**Comment by revolist** [comment]
Please post issue in @revolist/revogrid repo
