### ISSUE TITLE
Pasting a value in a select cell that is not in the select list breaks the view

### ISSUE THREAD

**Issue by dwaynehulsman** [revolist/revogrid-column-select#2]
When you paste a value in a select field that is not in the source of the select component the view will break leaving you with a string `undefined` being shown.

![image](https://user-images.githubusercontent.com/9630519/109011302-07f94e00-76b1-11eb-9ebc-d2676877cd9e.png)

**Comment by engrpatel21** [comment]
I am having the same issue. however the demo grid does not have this issue. have you been able to solve this problem?

**Comment by revolist** [comment]
Should be fixed now.
