### ISSUE TITLE
When using number values and textual labels the dropdown wont appear

### ISSUE THREAD

**Issue by dwaynehulsman** [revolist/revogrid-column-select#3]
In [this](https://codesandbox.io/s/black-bash-qc7sz?file=/src/App.vue) example I have created a simple table with a selectable color. Each of my colors represent a number, when you attempt to open the dropdown no results will be shown.

![image](https://user-images.githubusercontent.com/9630519/109989031-64d7b280-7d08-11eb-864b-0ce95fd136c8.png)

**Comment by HtheChemist** [comment]
This issue is caused by the strict not equal comparaison in editor.tsx.

Changing line 27 from:
`if (val !== this.editCell?.val) {`
to
`if (val != this.editCell?.val) {}`

Will solve the problem. Ill will make a pull request.
