### ISSUE TITLE
Should this component work with vue3

### ISSUE THREAD

**Issue by edwinmat** [revolist/revogrid-column-select#5]
Whatever I try, I cannot make this component work with the vue3-datagrid (No clickable down arrow appears). I tried with different versions of vue3 (<3.1) and different versions of vue3-datagrid. Should this be possible? Is there a working example somewhere?

**Comment by softrain73** [comment]
👍 I have same issue. Is there someone else?

**Comment by coralieO** [comment]
Same probleme here and i use vue3 and vite. If any one have an answer for this.

**Comment by revolist** [comment]
Yes, it's working ok.
